/**
 * Report Generator
 * Generates vulnerability reports in multiple formats
 */

class ReportGenerator {
  constructor() {
    this.formatters = {
      json: new JsonFormatter(),
      html: new HtmlFormatter(),
      markdown: new MarkdownFormatter(),
      csv: new CsvFormatter(),
      sarif: new SarifFormatter() // GitHub/VS Code compatible format
    };
  }

  async generateReport(scanResults, format = 'json', options = {}) {
    const formatter = this.formatters[format];
    if (!formatter) {
      throw new Error(`Unsupported report format: ${format}`);
    }

    const report = await formatter.format(scanResults, options);
    
    return {
      content: report,
      mimeType: formatter.mimeType,
      extension: formatter.extension,
      filename: this.generateFilename(format)
    };
  }

  generateFilename(format) {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    return `cve-audit-report-${timestamp}.${this.formatters[format].extension}`;
  }

  async generateMultipleFormats(scanResults, formats = ['json', 'html']) {
    const reports = {};
    
    for (const format of formats) {
      try {
        reports[format] = await this.generateReport(scanResults, format);
      } catch (error) {
        console.error(`Failed to generate ${format} report:`, error);
      }
    }
    
    return reports;
  }
}

// Base formatter class
class BaseFormatter {
  constructor() {
    this.mimeType = 'text/plain';
    this.extension = 'txt';
  }

  async format(scanResults, options) {
    throw new Error('format() must be implemented by subclass');
  }

  getSeverityEmoji(severity) {
    const emojis = {
      critical: '🔴',
      high: '🟠',
      medium: '🟡',
      low: '🔵'
    };
    return emojis[severity] || '⚪';
  }

  formatDate(date) {
    return new Date(date).toLocaleString();
  }
}

// JSON Formatter
class JsonFormatter extends BaseFormatter {
  constructor() {
    super();
    this.mimeType = 'application/json';
    this.extension = 'json';
  }

  async format(scanResults, options = {}) {
    const report = {
      reportVersion: '1.0.0',
      scanDate: scanResults.scannedAt,
      summary: scanResults.summary,
      totalVulnerabilities: this.getTotalVulnerabilities(scanResults.summary),
      vulnerabilities: scanResults.vulnerabilities.map(item => ({
        dependency: item.dependency,
        vulnerabilities: item.vulnerabilities.map(vuln => ({
          id: vuln.id,
          cve: vuln.cve,
          severity: this.getSeverityLevel(vuln.cvss),
          cvss: vuln.cvss,
          summary: vuln.summary,
          details: vuln.details,
          published: vuln.published,
          references: vuln.references,
          fixedVersions: vuln.fixedVersions
        })),
        remediation: item.remediation
      }))
    };

    if (options.pretty) {
      return JSON.stringify(report, null, 2);
    }
    
    return JSON.stringify(report);
  }

  getTotalVulnerabilities(summary) {
    return summary.critical + summary.high + summary.medium + summary.low;
  }

  getSeverityLevel(cvss) {
    if (cvss >= 9.0) return 'critical';
    if (cvss >= 7.0) return 'high';
    if (cvss >= 4.0) return 'medium';
    return 'low';
  }
}

// HTML Formatter
class HtmlFormatter extends BaseFormatter {
  constructor() {
    super();
    this.mimeType = 'text/html';
    this.extension = 'html';
  }

  async format(scanResults, options = {}) {
    const total = this.getTotalVulnerabilities(scanResults.summary);
    
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CVE Audit Report - ${this.formatDate(scanResults.scannedAt)}</title>
    <style>
        ${this.getStyles()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>CVE Security Audit Report</h1>
            <p class="scan-date">Scanned on: ${this.formatDate(scanResults.scannedAt)}</p>
        </header>

        <section class="summary">
            <h2>Executive Summary</h2>
            <div class="stats-grid">
                ${this.renderSummaryStats(scanResults.summary)}
            </div>
            <p class="total-count">Total vulnerabilities found: <strong>${total}</strong></p>
        </section>

        ${total > 0 ? this.renderVulnerabilities(scanResults.vulnerabilities) : this.renderNoVulnerabilities()}

        <footer>
            <p>Generated by Gaia CVE Scanner</p>
        </footer>
    </div>
</body>
</html>`;
  }

  getStyles() {
    return `
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 0;
            background: #f5f5f5;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: white;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        header {
            border-bottom: 2px solid #e0e0e0;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        h1 {
            color: #2c3e50;
            margin: 0 0 10px 0;
        }
        .scan-date {
            color: #666;
            font-size: 14px;
        }
        .summary {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 30px;
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 20px;
            margin: 20px 0;
        }
        .stat-card {
            background: white;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .stat-value {
            font-size: 36px;
            font-weight: bold;
            margin: 10px 0;
        }
        .stat-label {
            font-size: 14px;
            text-transform: uppercase;
            opacity: 0.7;
        }
        .critical { color: #d32f2f; }
        .high { color: #f44336; }
        .medium { color: #ff9800; }
        .low { color: #2196f3; }
        .vulnerability-section {
            margin-bottom: 30px;
            border: 1px solid #e0e0e0;
            border-radius: 8px;
            overflow: hidden;
        }
        .dependency-header {
            background: #f5f5f5;
            padding: 15px;
            font-weight: bold;
        }
        .vulnerability-list {
            padding: 20px;
        }
        .vulnerability-item {
            margin-bottom: 20px;
            padding-bottom: 20px;
            border-bottom: 1px solid #eee;
        }
        .vulnerability-item:last-child {
            border-bottom: none;
            margin-bottom: 0;
            padding-bottom: 0;
        }
        .vuln-header {
            display: flex;
            align-items: center;
            gap: 10px;
            margin-bottom: 10px;
        }
        .severity-badge {
            padding: 4px 12px;
            border-radius: 4px;
            color: white;
            font-size: 12px;
            font-weight: bold;
            text-transform: uppercase;
        }
        .severity-critical { background: #d32f2f; }
        .severity-high { background: #f44336; }
        .severity-medium { background: #ff9800; }
        .severity-low { background: #2196f3; }
        .remediation {
            background: #e8f5e9;
            padding: 15px;
            border-radius: 4px;
            margin-top: 15px;
        }
        .command {
            background: #263238;
            color: #aed581;
            padding: 10px;
            border-radius: 4px;
            font-family: monospace;
            margin: 5px 0;
            overflow-x: auto;
        }
        .no-vulnerabilities {
            text-align: center;
            padding: 60px;
            color: #4caf50;
        }
        .no-vulnerabilities .icon {
            font-size: 48px;
            margin-bottom: 20px;
        }
        footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #e0e0e0;
            text-align: center;
            color: #666;
            font-size: 14px;
        }
    `;
  }

  renderSummaryStats(summary) {
    return `
        <div class="stat-card">
            <div class="stat-value critical">${summary.critical}</div>
            <div class="stat-label">Critical</div>
        </div>
        <div class="stat-card">
            <div class="stat-value high">${summary.high}</div>
            <div class="stat-label">High</div>
        </div>
        <div class="stat-card">
            <div class="stat-value medium">${summary.medium}</div>
            <div class="stat-label">Medium</div>
        </div>
        <div class="stat-card">
            <div class="stat-value low">${summary.low}</div>
            <div class="stat-label">Low</div>
        </div>
    `;
  }

  renderVulnerabilities(vulnerabilities) {
    return `
        <section class="vulnerabilities">
            <h2>Vulnerability Details</h2>
            ${vulnerabilities.map(item => this.renderDependencySection(item)).join('')}
        </section>
    `;
  }

  renderDependencySection(item) {
    const { dependency, vulnerabilities, remediation } = item;
    
    return `
        <div class="vulnerability-section">
            <div class="dependency-header">
                ${dependency.name} @ ${dependency.version} (${dependency.ecosystem})
            </div>
            <div class="vulnerability-list">
                ${vulnerabilities.map(vuln => this.renderVulnerability(vuln)).join('')}
                ${remediation.actions.length > 0 ? this.renderRemediation(remediation) : ''}
            </div>
        </div>
    `;
  }

  renderVulnerability(vuln) {
    const severity = this.getSeverityLevel(vuln.cvss);
    
    return `
        <div class="vulnerability-item">
            <div class="vuln-header">
                <span class="severity-badge severity-${severity}">${severity}</span>
                <span>${vuln.cve || vuln.id}</span>
                <span>CVSS: ${vuln.cvss.toFixed(1)}</span>
            </div>
            <p>${vuln.summary}</p>
            ${vuln.fixedVersions.length > 0 ? `
                <p><strong>Fixed in:</strong> ${vuln.fixedVersions.join(', ')}</p>
            ` : ''}
        </div>
    `;
  }

  renderRemediation(remediation) {
    return `
        <div class="remediation">
            <h4>Remediation</h4>
            ${remediation.actions.map(action => `
                <div class="command">${action.command}</div>
            `).join('')}
            ${remediation.breakingChanges ? `
                <p style="color: #f44336; margin-top: 10px;">
                    ⚠️ Warning: This update includes breaking changes
                </p>
            ` : ''}
        </div>
    `;
  }

  renderNoVulnerabilities() {
    return `
        <section class="no-vulnerabilities">
            <div class="icon">✅</div>
            <h2>No Vulnerabilities Found</h2>
            <p>Your dependencies are secure and up to date!</p>
        </section>
    `;
  }

  getTotalVulnerabilities(summary) {
    return summary.critical + summary.high + summary.medium + summary.low;
  }

  getSeverityLevel(cvss) {
    if (cvss >= 9.0) return 'critical';
    if (cvss >= 7.0) return 'high';
    if (cvss >= 4.0) return 'medium';
    return 'low';
  }
}

// Markdown Formatter
class MarkdownFormatter extends BaseFormatter {
  constructor() {
    super();
    this.mimeType = 'text/markdown';
    this.extension = 'md';
  }

  async format(scanResults, options = {}) {
    const total = this.getTotalVulnerabilities(scanResults.summary);
    
    let markdown = `# CVE Security Audit Report\n\n`;
    markdown += `**Scanned on:** ${this.formatDate(scanResults.scannedAt)}\n\n`;
    
    // Summary
    markdown += `## Executive Summary\n\n`;
    markdown += `| Severity | Count |\n`;
    markdown += `|----------|-------|\n`;
    markdown += `| ${this.getSeverityEmoji('critical')} Critical | ${scanResults.summary.critical} |\n`;
    markdown += `| ${this.getSeverityEmoji('high')} High | ${scanResults.summary.high} |\n`;
    markdown += `| ${this.getSeverityEmoji('medium')} Medium | ${scanResults.summary.medium} |\n`;
    markdown += `| ${this.getSeverityEmoji('low')} Low | ${scanResults.summary.low} |\n`;
    markdown += `| **Total** | **${total}** |\n\n`;
    
    if (total === 0) {
      markdown += `### ✅ No vulnerabilities found!\n\n`;
      markdown += `Your dependencies are secure and up to date.\n\n`;
    } else {
      markdown += `## Vulnerability Details\n\n`;
      
      for (const item of scanResults.vulnerabilities) {
        markdown += this.renderDependencySection(item);
      }
    }
    
    markdown += `---\n\n`;
    markdown += `*Generated by Gaia CVE Scanner*\n`;
    
    return markdown;
  }

  renderDependencySection(item) {
    const { dependency, vulnerabilities, remediation } = item;
    
    let section = `### 📦 ${dependency.name} @ ${dependency.version} (${dependency.ecosystem})\n\n`;
    
    for (const vuln of vulnerabilities) {
      section += this.renderVulnerability(vuln);
    }
    
    if (remediation.actions.length > 0) {
      section += `#### 💡 Remediation\n\n`;
      for (const action of remediation.actions) {
        section += `\`\`\`bash\n${action.command}\n\`\`\`\n\n`;
      }
      
      if (remediation.breakingChanges) {
        section += `> ⚠️ **Warning:** This update includes breaking changes\n\n`;
      }
    }
    
    return section;
  }

  renderVulnerability(vuln) {
    const severity = this.getSeverityLevel(vuln.cvss);
    const emoji = this.getSeverityEmoji(severity);
    
    let content = `#### ${emoji} ${vuln.cve || vuln.id} - ${severity.toUpperCase()} (CVSS: ${vuln.cvss.toFixed(1)})\n\n`;
    content += `${vuln.summary}\n\n`;
    
    if (vuln.fixedVersions.length > 0) {
      content += `**Fixed in:** ${vuln.fixedVersions.join(', ')}\n\n`;
    }
    
    return content;
  }

  getTotalVulnerabilities(summary) {
    return summary.critical + summary.high + summary.medium + summary.low;
  }

  getSeverityLevel(cvss) {
    if (cvss >= 9.0) return 'critical';
    if (cvss >= 7.0) return 'high';
    if (cvss >= 4.0) return 'medium';
    return 'low';
  }
}

// CSV Formatter
class CsvFormatter extends BaseFormatter {
  constructor() {
    super();
    this.mimeType = 'text/csv';
    this.extension = 'csv';
  }

  async format(scanResults, options = {}) {
    const rows = [];
    
    // Header
    rows.push([
      'Dependency',
      'Version',
      'Ecosystem',
      'Vulnerability ID',
      'CVE',
      'Severity',
      'CVSS Score',
      'Summary',
      'Fixed Versions',
      'Remediation Command'
    ]);
    
    // Data rows
    for (const item of scanResults.vulnerabilities) {
      const { dependency, vulnerabilities, remediation } = item;
      
      for (const vuln of vulnerabilities) {
        const severity = this.getSeverityLevel(vuln.cvss);
        const remediationCmd = remediation.actions[0]?.command || '';
        
        rows.push([
          dependency.name,
          dependency.version,
          dependency.ecosystem,
          vuln.id,
          vuln.cve || '',
          severity,
          vuln.cvss.toFixed(1),
          this.escapeCSV(vuln.summary),
          vuln.fixedVersions.join('; '),
          this.escapeCSV(remediationCmd)
        ]);
      }
    }
    
    return rows.map(row => row.join(',')).join('\n');
  }

  escapeCSV(value) {
    if (!value) return '';
    
    // Escape quotes and wrap in quotes if contains comma, newline, or quotes
    if (value.includes(',') || value.includes('\n') || value.includes('"')) {
      return `"${value.replace(/"/g, '""')}"`;
    }
    
    return value;
  }

  getSeverityLevel(cvss) {
    if (cvss >= 9.0) return 'critical';
    if (cvss >= 7.0) return 'high';
    if (cvss >= 4.0) return 'medium';
    return 'low';
  }
}

// SARIF Formatter (for GitHub/VS Code integration)
class SarifFormatter extends BaseFormatter {
  constructor() {
    super();
    this.mimeType = 'application/sarif+json';
    this.extension = 'sarif';
  }

  async format(scanResults, options = {}) {
    const sarif = {
      version: '2.1.0',
      runs: [{
        tool: {
          driver: {
            name: 'Gaia CVE Scanner',
            version: '1.0.0',
            informationUri: 'https://github.com/gaia/cve-scanner',
            rules: this.generateRules(scanResults)
          }
        },
        results: this.generateResults(scanResults)
      }]
    };
    
    return JSON.stringify(sarif, null, 2);
  }

  generateRules(scanResults) {
    const rules = [];
    const seenRules = new Set();
    
    for (const item of scanResults.vulnerabilities) {
      for (const vuln of item.vulnerabilities) {
        const ruleId = vuln.cve || vuln.id;
        
        if (!seenRules.has(ruleId)) {
          seenRules.add(ruleId);
          
          rules.push({
            id: ruleId,
            name: ruleId,
            shortDescription: {
              text: vuln.summary
            },
            fullDescription: {
              text: vuln.details || vuln.summary
            },
            defaultConfiguration: {
              level: this.getSarifLevel(vuln.cvss)
            },
            properties: {
              'security-severity': vuln.cvss.toString()
            }
          });
        }
      }
    }
    
    return rules;
  }

  generateResults(scanResults) {
    const results = [];
    
    for (const item of scanResults.vulnerabilities) {
      const { dependency, vulnerabilities } = item;
      
      for (const vuln of vulnerabilities) {
        results.push({
          ruleId: vuln.cve || vuln.id,
          level: this.getSarifLevel(vuln.cvss),
          message: {
            text: `${dependency.name}@${dependency.version} has vulnerability: ${vuln.summary}`
          },
          locations: [{
            physicalLocation: {
              artifactLocation: {
                uri: this.getDependencyFile(dependency.ecosystem)
              }
            }
          }]
        });
      }
    }
    
    return results;
  }

  getSarifLevel(cvss) {
    if (cvss >= 9.0) return 'error';
    if (cvss >= 7.0) return 'error';
    if (cvss >= 4.0) return 'warning';
    return 'note';
  }

  getDependencyFile(ecosystem) {
    const files = {
      npm: 'package.json',
      pip: 'requirements.txt',
      pub: 'pubspec.yaml'
    };
    return files[ecosystem] || 'unknown';
  }
}

export default ReportGenerator;